name: Deploy Server to Heroku

on:
  push:
    branches: [ 'master' ]
    paths: [ 'server/**', '.github/workflows/deploy-server.yml' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Embed secrets
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS_CONTENTS > service-account-file.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENTS}}
      - name: Build and deploy Docker image
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ch22-api" # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: server
          healthcheck: "https://ch22-api.herokuapp.com/health"
          delay: 5
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGO_ADMIN: ${{secrets.MONGO_ADMIN}}
          HD_MONGO_USER: ${{secrets.MONGO_USER}}
          HD_GOOGLE_APPLICATION_CREDENTIALS: service-account-file.json

